version: '3.9'

services:
  db-postgresql:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=backend_challenge
      - POSTGRES_USER=backend_challenge
      - POSTGRES_PASSWORD=backend_challenge123

  backend_challenge:
    container_name: backend_app
    image: backend_challenge:1.0.0
    build: .
    ports:
      - 8081:8081
    volumes:
      - pgdata:/var/lib/postgresql/data
    #env_file:
      #- backnd.env
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db-postgresql:5432/backend_challenge
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgresql:5432/backend_challenge
      - SPRING_DATASOURCE_USERNAME=backend_challenge
      - SPRING_DATASOURCE_PASSWORD=backend_challenge123
    depends_on:
      - db-postgresql

volumes:
  pgdata: